/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.view;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import main.controller.GameController;

/**
 *
 * @author gabri
 */
public class BoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form BoardPanel
     */
    private ImageIcon boardGraphic;
    private GameController gameController;
    
    public BoardPanel() {
        initComponents();
        this.boardGraphic = new ImageIcon("./src/main/resources/img/TableroParchis.png"); 
        
    }
  
    public void setController(GameController controller){
        this.gameController = controller;
    }
    public void listen(GameController controller){
        this.gameController = controller;
        addMouseListener(controller);
    }
    
   @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        //g.drawString("Esto es una prueba", 80, 70);
        
        this.boardGraphic.paintIcon(this, g, 0, 0);
        if(gameController != null){
        this.gameController.draw(this, g);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
