/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.view;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import main.controller.GameController;

/**
 *
 * @author Gabriel Mora Hernandez
 */
public class BoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form BoardPanel
     */
    private ImageIcon boardGraphic;
    private GameController gameController;
    
    public BoardPanel() {
        initComponents();
        this.boardGraphic = new ImageIcon("./src/main/resources/img/TableroParchis.png"); 
        
    }
    
    
   
  
    public void setController(GameController controller){
        this.gameController = controller;
    }
    public void listen(GameController controller){
        this.gameController = controller;
        addMouseListener(controller);
    }
    
   @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
         
        
        this.boardGraphic.paintIcon(this, g, 0, 0);
        if(gameController != null){
        this.gameController.draw(this, g);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgfichaAmarilla = new javax.swing.JLabel();
        imgfichaAzul = new javax.swing.JLabel();
        imgfichaRoja = new javax.swing.JLabel();
        imgfichaVerde = new javax.swing.JLabel();
        lblFondoParchis = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgfichaAmarilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fichaAmarilla.png"))); // NOI18N
        add(imgfichaAmarilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, -1, -1));

        imgfichaAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fichaAzul.png"))); // NOI18N
        add(imgfichaAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        imgfichaRoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fichaRoja.png"))); // NOI18N
        add(imgfichaRoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        imgfichaVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fichaVerde.png"))); // NOI18N
        add(imgfichaVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        lblFondoParchis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TableroParchis.png"))); // NOI18N
        add(lblFondoParchis, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 680, 700));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgfichaAmarilla;
    private javax.swing.JLabel imgfichaAzul;
    private javax.swing.JLabel imgfichaRoja;
    private javax.swing.JLabel imgfichaVerde;
    private javax.swing.JLabel lblFondoParchis;
    // End of variables declaration//GEN-END:variables
}
