/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.view;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import main.controller.GameController;

/**
 *
 * @author Gabriel Mora Hernandez
 */
public class ControllPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControllPanel
     */
    private ImageIcon background;
    private GameController controller;
    private ImageIcon boardGraphic;
    
    public ControllPanel() {
        initComponents();
        this.background = new ImageIcon("./src/main/resources/img/tableroCaja.png");
        this.boardGraphic = new ImageIcon("./src/main/resources/img/TableroParchis.png");
        
    }

   public void setController(GameController controller){
        this.controller = controller;
        listen();
    }
    
   public void listen(){
        this.btnDado.addActionListener(controller);
        this.btnJugador1.addActionListener(controller);
        this.btnJugador2.addActionListener(controller);
        this.btnJugar.addActionListener(controller);
        this.btnSalir.addActionListener(controller);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnJugador2 = new javax.swing.JButton();
        btnJugador1 = new javax.swing.JButton();
        btnPuntaje = new javax.swing.JLabel();
        btnDado = new javax.swing.JButton();
        lblFondoTablero = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setBackground(new java.awt.Color(0, 204, 204));
        btnJugar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("Jugar");
        btnJugar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 120, 40));

        btnSalir.setBackground(new java.awt.Color(0, 204, 204));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, 100, 40));

        btnJugador2.setBackground(new java.awt.Color(153, 255, 204));
        btnJugador2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnJugador2.setText("Jugador2");
        btnJugador2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btnJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 100, 80));

        btnJugador1.setBackground(new java.awt.Color(153, 255, 204));
        btnJugador1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnJugador1.setText("Jugador1");
        btnJugador1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btnJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 100, 80));

        btnPuntaje.setBackground(new java.awt.Color(204, 255, 204));
        btnPuntaje.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnPuntaje.setText("Puntaje");
        btnPuntaje.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btnPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 90, 50));

        btnDado.setBackground(new java.awt.Color(242, 242, 242));
        btnDado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnDado.setText("Dado");
        btnDado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 70, 50));

        lblFondoTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tableroCaja.png"))); // NOI18N
        lblFondoTablero.setText("jLabel1");
        lblFondoTablero.setMaximumSize(new java.awt.Dimension(900, 700));
        lblFondoTablero.setMinimumSize(new java.awt.Dimension(900, 700));
        lblFondoTablero.setPreferredSize(new java.awt.Dimension(900, 700));
        add(lblFondoTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 720));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnJugador1;
    private javax.swing.JButton btnJugador2;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel btnPuntaje;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblFondoTablero;
    // End of variables declaration//GEN-END:variables
}
