/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.view;

import main.controller.MainController;

/**
 *
 * @author gabri
 */
public class GUICreditos extends javax.swing.JFrame {
    private MainController controller;

    /**
     * Creates new form GUICreditos
     */
    public GUICreditos(MainController controller) {
        initComponents();
        this.controller = controller;
        listen();
    }

    public void listen(){
        this.btnAtras.addActionListener(controller);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreditos = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lblHechoPor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFondoCreditos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreditos.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblCreditos.setText("Creditos");
        getContentPane().add(lblCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 46));

        btnAtras.setBackground(new java.awt.Color(204, 204, 255));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtras.setContentAreaFilled(false);
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 86, 41));

        lblHechoPor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblHechoPor.setText("Hecho Por: ");
        getContentPane().add(lblHechoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel2.setText("Gabriel Jesús Mora Hernández");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        lblFondoCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoCreditos.png"))); // NOI18N
        getContentPane().add(lblFondoCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 560, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblFondoCreditos;
    private javax.swing.JLabel lblHechoPor;
    // End of variables declaration//GEN-END:variables
}
