/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.view;

import main.controller.MainController;

/**
 *
 * @author gabri
 */
public class GUIHistoria extends javax.swing.JFrame {
    private MainController controller;


    /**
     * Creates new form GUIHistoria
     */
    public GUIHistoria(MainController controller) {
        initComponents();
        this.controller = controller;
        listen();
    }

    public void listen(){
        this.btnAtras.addActionListener(controller);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHistoria = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lblHistory = new javax.swing.JLabel();
        lblHistory1 = new javax.swing.JLabel();
        lblHistory2 = new javax.swing.JLabel();
        lblHistory3 = new javax.swing.JLabel();
        lblfFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHistoria.setBackground(new java.awt.Color(204, 204, 255));
        lblHistoria.setFont(new java.awt.Font("Perpetua", 3, 36)); // NOI18N
        lblHistoria.setText("Historia");
        getContentPane().add(lblHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        btnAtras.setBackground(new java.awt.Color(204, 204, 255));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtras.setContentAreaFilled(false);
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 317, 85, 46));

        lblHistory.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblHistory.setText("de la isla y alzarse con la victoria");
        getContentPane().add(lblHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        lblHistory1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblHistory1.setText("para llegar hasta la meta y convertirse en los nuevos dueños");
        getContentPane().add(lblHistory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 60));

        lblHistory2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblHistory2.setText("Usarán a criaturas originarias del mar como compañeros");
        getContentPane().add(lblHistory2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        lblHistory3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblHistory3.setText("Dos jugadores lucharán por ver quien es el Rey de la isla");
        getContentPane().add(lblHistory3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblfFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoHistoria.png"))); // NOI18N
        getContentPane().add(lblfFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel lblHistoria;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblHistory1;
    private javax.swing.JLabel lblHistory2;
    private javax.swing.JLabel lblHistory3;
    private javax.swing.JLabel lblfFondo;
    // End of variables declaration//GEN-END:variables
}
