/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.view;

import java.awt.event.ActionListener;

/**
 *
 * @author gabri
 */
public class GUIInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIInicio.class.getName());

    /**
     * Creates new form GUIInicio
     */
    public GUIInicio() {
        initComponents();
    }

     public void setListener(ActionListener controller){
        this.btnInstrucciones.addActionListener(controller);
        this.btnHistoria.addActionListener(controller);
        this.btnCreditos.addActionListener(controller);
        this.btnJugar.addActionListener(controller);
        
        
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnInstrucciones = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        lblWelcome.setText("¡Bienvenido a Parchís!");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 50, -1, 37));

        btnInstrucciones.setBackground(new java.awt.Color(132, 176, 199));
        btnInstrucciones.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 191, 150, 43));

        btnCreditos.setBackground(new java.awt.Color(132, 176, 199));
        btnCreditos.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnCreditos.setForeground(new java.awt.Color(255, 255, 255));
        btnCreditos.setText("Creditos");
        btnCreditos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 312, 100, 42));

        btnHistoria.setBackground(new java.awt.Color(132, 176, 199));
        btnHistoria.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnHistoria.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoria.setText("Historia");
        btnHistoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 252, 100, 42));

        btnJugar.setBackground(new java.awt.Color(132, 176, 199));
        btnJugar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("Jugar");
        btnJugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 130, 80, 43));

        imgFondo.setText("jLabel1");
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
