/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.view;

import main.controller.MainController;

/**
 *
 * @author gabri
 */
public class GUIInstrucciones extends javax.swing.JFrame {
    private MainController controller;
   

    /**
     * Creates new form GUIInstrucciones
     */
    public GUIInstrucciones(MainController controller) {
        initComponents();
        this.controller = controller;
        listen();
    }

    public void listen(){
        this.btnAtras.addActionListener(controller);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstrucciones = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInstrucciones.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblInstrucciones.setText("Instrucciones");
        lblInstrucciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        btnAtras.setBackground(new java.awt.Color(204, 204, 255));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtras.setContentAreaFilled(false);
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 332, 97, 46));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoInstrucciones.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInstrucciones;
    // End of variables declaration//GEN-END:variables
}
