/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.view;

import main.controller.GameController;

/**
 *
 * @author Gabriel Mora Hernandez
 */
public class GUITablero extends javax.swing.JFrame {
    
 

    /**
     * Creates new form GUITablero
     */
    public GUITablero(GameController gameController) {
        initComponents();
        this.controllPanel1.setController(gameController);//        this.boardPanel1.setController(gameController);
        
    }
    
    public ControllPanel getPanelControll(){
        return controllPanel1;
    }
    public BoardPanel getBoardPanel(){
        return boardPanel1;
    }
//    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controllPanel1 = new main.view.ControllPanel();
        boardPanel1 = new main.view.BoardPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(controllPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));
        getContentPane().add(boardPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 670, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.view.BoardPanel boardPanel1;
    private main.view.ControllPanel controllPanel1;
    // End of variables declaration//GEN-END:variables
}
