/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.view;

import main.controller.GameController;

/**
 *
 * @author Gabriel Mora Hernandez
 */
public class GUITablero extends javax.swing.JFrame {
    
 

    /**
     * Creates new form GUITablero
     */
    public GUITablero(GameController gameController) {
        initComponents();
        this.controllPanel2.setController(gameController);//        this.boardPanel1.setController(gameController);
        
    }
    
    public ControllPanel getPanelControll(){
        return controllPanel2;
    }
    public BoardPanel getBoardPanel(){
        return boardPanel1;
    }
//    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardPanel1 = new main.view.BoardPanel();
        controllPanel2 = new main.view.ControllPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout boardPanel1Layout = new javax.swing.GroupLayout(boardPanel1);
        boardPanel1.setLayout(boardPanel1Layout);
        boardPanel1Layout.setHorizontalGroup(
            boardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        boardPanel1Layout.setVerticalGroup(
            boardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(boardPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 670, 680));
        getContentPane().add(controllPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.view.BoardPanel boardPanel1;
    private main.view.ControllPanel controllPanel2;
    // End of variables declaration//GEN-END:variables
}
