/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.view;

import java.awt.event.ActionListener;
import main.controller.GameController;

/**
 *
 * @author gabri
 */
public class PanelInstrucciones extends javax.swing.JPanel {

    /**
     * Creates new form PanelInstrucciones
     */
    public PanelInstrucciones() {
        initComponents();
    }

    public void setController(GameController controller){
        this.listen(controller);
    }
   
    public void listen(ActionListener controller){
        this.btnAtras.addActionListener(controller);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        lblInstrucciones = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setBackground(new java.awt.Color(204, 204, 255));
        btnAtras.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 90, 40));

        lblInstrucciones.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblInstrucciones.setText("Instrucciones");
        add(lblInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel lblInstrucciones;
    // End of variables declaration//GEN-END:variables
}
